// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdultDisplay = { display_name: string, role: string, email: string | null, phone: string | null, ypt_status: string | null, ypt_style: string | null, ypt_sort_date: string | null, position_trained: string | null, membership_status: string | null, membership_style: string | null, membership_sort_date: string | null, user_id: number | null, first_name: string, last_name: string, position: string | null, member_id: string | null, };
