// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AwardDisplay = { name: string, date_display: string, type_display: string, is_awarded: boolean, is_completed: boolean, status: string, progress_percent: number | null, };
