// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MeritBadgeRequirementDisplay } from "./MeritBadgeRequirementDisplay";

export type BadgeRequirementsResponseDisplay = { requirements: Array<MeritBadgeRequirementDisplay>, version: string | null, counselor_name: string, counselor_phone: string, counselor_email: string | null, };
