// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary of badge completion counts.
 */
export type BadgeSummary = { completed: number, in_progress: number, eagle_completed: number, eagle_required_total: number, };
