// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CacheAges = { youth: string | null, adults: string | null, parents: string | null, patrols: string | null, events: string | null, advancement: string | null, };
