// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LeadershipDisplay = { name: string, date_range: string, days_display: string, is_current: boolean, patrol: string | null, sort_date: string, };
