// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A leader with name information.
 */
export type Leader = { first_name: string, last_name: string, };
