// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Meeting location address.
 */
export type MeetingLocation = { address_line1: string | null, address_line2: string | null, city: string | null, state: string | null, zip: string | null, };
