// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MeritBadgeDisplay = { name: string, id: number, is_completed: boolean, is_awarded: boolean, is_eagle_required: boolean, progress_percent: number | null, formatted_date_completed: string, status: string, status_label: string, status_category: string, counselor_name: string, counselor_phone: string, sort_date: string, date_completed: string | null, percent_completed: number | null, };
