// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Patrol = { subUnitGuid: string, subUnitName: string, memberCount: number | null, patrolLeaderUserId: number | null, patrolLeaderName: string | null, };
