// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RankProgressDisplay = { rank_name: string, rank_id: number, sort_order: number, is_completed: boolean, is_awarded: boolean, formatted_date_completed: string, formatted_date_awarded: string, display_date: string, status_label: string, status_category: string, progress_percent: number | null, date_completed: string | null, date_awarded: string | null, percent_completed: number | null, requirements_completed: number | null, requirements_total: number | null, };
