// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MeetingLocation } from "./MeetingLocation";
import type { UnitContact } from "./UnitContact";

/**
 * Unit registration and contact information.
 */
export type UnitInfo = { name: string | null, website: string | null, registration_url: string | null, district_name: string | null, council_name: string | null, charter_org_name: string | null, charter_expiry: string | null, meeting_location: MeetingLocation | null, contacts: Array<UnitContact>, charter_status_display: string | null, charter_expired: boolean | null, };
