// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BadgeSummary } from "./BadgeSummary";
import type { MeritBadgeDisplay } from "./MeritBadgeDisplay";

/**
 * Wrapper DTO that bundles badges with a computed summary.
 */
export type YouthBadgesResponse = { badges: Array<MeritBadgeDisplay>, summary: BadgeSummary, };
