// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BadgePivotScout = { user_id: number, badge_id: number, display_name: string, formatted_date_completed: string, formatted_date_awarded: string, sort_date: string, percent_completed: number | null, is_completed: boolean, is_awarded: boolean, status: string, };
