// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BadgePivotScout } from "./BadgePivotScout";

export type BadgePivotEntry = { badge_name: string, is_eagle_required: boolean, count: number, scouts: Array<BadgePivotScout>, };
