// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EventDisplay = { formatted_date: string, formatted_start: string, formatted_end: string, derived_type: string, description_text: string, going_count: number, not_going_count: number, id: number, name: string, start_date: string | null, end_date: string | null, location: string | null, event_type: string | null, rsvp: boolean, unit_id: number | null, };
