// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EventGuestDisplay = { display_name: string, status: string, is_youth: boolean, user_id: number, first_name: string, last_name: string, };
