// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MeritBadgeRequirementDisplay = { number: string, text: string, is_completed: boolean, formatted_date_completed: string, };
