// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ParentDisplay = { name: string, email: string | null, phone: string | null, address_line1: string | null, address_line2: string | null, youth_user_id: number | null, };
