// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RankPivotScout } from "./RankPivotScout";

export type RankPivotEntry = { rank_name: string, rank_order: number, count: number, scouts: Array<RankPivotScout>, };
