// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A commissioner assigned to the unit.
 */
export type Commissioner = { first_name: string | null, last_name: string | null, position: string | null, };
