// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Leader } from "./Leader";

/**
 * Key 3 leadership positions for a unit.
 */
export type Key3Leaders = { scoutmaster: Leader | null, committee_chair: Leader | null, charter_org_rep: Leader | null, };
