// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Organization profile information.
 */
export type OrgProfile = { name: string | null, full_name: string | null, charter_org_name: string | null, charter_exp_date: string | null, charter_status: string | null, };
