// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A unit contact person.
 */
export type UnitContact = { first_name: string | null, last_name: string | null, email: string | null, phone: string | null, };
